import { AIModel } from '../types';

export const INITIAL_MODELS: AIModel[] = [
  // 1. Google Gemini (Free Tier Catalog)
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    displayName: 'Gemini 2.0 Flash (Free Tier Catalog)',
    provider: 'Google Gemini',
    providerModelId: 'models/gemini-2.0-flash',
    tier: 'free',
    costPer1kTokens: '$0.00 (Catalog Free Tier)',
    inputCost: '$0.00 / 1M',
    outputCost: '$0.00 / 1M',
    contextWindow: '1,048,576 tokens',
    status: 'untested',
    capabilities: ['coding', 'reasoning', 'vision', 'tool_use', 'fast'],
    codingScore: 92,
    online: true,
    isLocal: false,
    availability: 'available'
  },
  {
    id: 'gemini-2.0-flash-thinking',
    name: 'Gemini 2.0 Flash Thinking',
    displayName: 'Gemini 2.0 Flash Thinking Exp',
    provider: 'Google Gemini',
    providerModelId: 'models/gemini-2.0-flash-thinking-exp',
    tier: 'free',
    costPer1kTokens: '$0.00 (Catalog Free Tier)',
    inputCost: '$0.00 / 1M',
    outputCost: '$0.00 / 1M',
    contextWindow: '1,048,576 tokens',
    status: 'untested',
    capabilities: ['reasoning', 'coding', 'tool_use'],
    codingScore: 94,
    online: true,
    isLocal: false,
    availability: 'available'
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    displayName: 'Gemini 1.5 Pro (Deep Architecture)',
    provider: 'Google Gemini',
    providerModelId: 'models/gemini-1.5-pro',
    tier: 'free',
    costPer1kTokens: '$0.00 (Catalog Free Tier)',
    inputCost: '$0.00 / 1M',
    outputCost: '$0.00 / 1M',
    contextWindow: '2,097,152 tokens',
    status: 'untested',
    capabilities: ['coding', 'reasoning', 'vision', 'tool_use'],
    codingScore: 95,
    online: true,
    isLocal: false,
    availability: 'available'
  },

  // 2. OpenRouter Free Tier Models (Catalog)
  {
    id: 'openrouter-qwen-coder',
    name: 'Qwen 2.5 Coder 32B Free',
    displayName: 'Qwen 2.5 Coder 32B Instruct (Free)',
    provider: 'OpenRouter',
    providerModelId: 'qwen/qwen-2.5-coder-32b-instruct:free',
    tier: 'free',
    costPer1kTokens: '$0.00 (OpenRouter Free Gateway)',
    inputCost: '$0.00',
    outputCost: '$0.00',
    contextWindow: '131,072 tokens',
    status: 'untested',
    capabilities: ['coding', 'tool_use', 'reasoning'],
    codingScore: 91,
    online: true,
    isLocal: false,
    availability: 'available'
  },
  {
    id: 'openrouter-llama-3.3-70b',
    name: 'Llama 3.3 70B Instruct Free',
    displayName: 'Meta Llama 3.3 70B Instruct (Free)',
    provider: 'OpenRouter',
    providerModelId: 'meta-llama/llama-3.3-70b-instruct:free',
    tier: 'free',
    costPer1kTokens: '$0.00 (OpenRouter Free Gateway)',
    inputCost: '$0.00',
    outputCost: '$0.00',
    contextWindow: '131,072 tokens',
    status: 'untested',
    capabilities: ['coding', 'reasoning', 'tool_use'],
    codingScore: 89,
    online: true,
    isLocal: false,
    availability: 'available'
  },
  {
    id: 'openrouter-deepseek-r1-free',
    name: 'DeepSeek R1 Free',
    displayName: 'DeepSeek R1 Reasoning (Free)',
    provider: 'OpenRouter',
    providerModelId: 'deepseek/deepseek-r1:free',
    tier: 'free',
    costPer1kTokens: '$0.00 (OpenRouter Free Gateway)',
    inputCost: '$0.00',
    outputCost: '$0.00',
    contextWindow: '64,000 tokens',
    status: 'untested',
    capabilities: ['reasoning', 'coding'],
    codingScore: 96,
    online: true,
    isLocal: false,
    availability: 'available'
  },

  // 3. Ollama 100% Local GPU/CPU (Offline Catalog)
  {
    id: 'ollama-qwen-coder',
    name: 'Qwen 2.5 Coder 7B Local',
    displayName: 'Qwen 2.5 Coder 7B (Ollama Local)',
    provider: 'Ollama Local',
    providerModelId: 'qwen2.5-coder:7b',
    tier: 'free',
    costPer1kTokens: '$0.00 (100% Private Offline)',
    inputCost: '$0.00 (Local Compute)',
    outputCost: '$0.00 (Local Compute)',
    contextWindow: '32,768 tokens',
    status: 'untested',
    capabilities: ['coding', 'fast'],
    codingScore: 86,
    online: false,
    isLocal: true,
    availability: 'available'
  },
  {
    id: 'ollama-deepseek-r1-8b',
    name: 'DeepSeek R1 8B Local',
    displayName: 'DeepSeek R1 Distill 8B (Local)',
    provider: 'Ollama Local',
    providerModelId: 'deepseek-r1:8b',
    tier: 'free',
    costPer1kTokens: '$0.00 (100% Private Offline)',
    inputCost: '$0.00 (Local Compute)',
    outputCost: '$0.00 (Local Compute)',
    contextWindow: '32,768 tokens',
    status: 'untested',
    capabilities: ['reasoning', 'coding'],
    codingScore: 88,
    online: false,
    isLocal: true,
    availability: 'available'
  },
  {
    id: 'ollama-llama-3.2-3b',
    name: 'Llama 3.2 3B Local',
    displayName: 'Llama 3.2 3B Lightweight (Local)',
    provider: 'Ollama Local',
    providerModelId: 'llama3.2:3b',
    tier: 'free',
    costPer1kTokens: '$0.00 (100% Private Offline)',
    inputCost: '$0.00 (Local Compute)',
    outputCost: '$0.00 (Local Compute)',
    contextWindow: '16,384 tokens',
    status: 'untested',
    capabilities: ['fast'],
    codingScore: 78,
    online: false,
    isLocal: true,
    availability: 'available'
  },

  // 4. Groq Ultra-Fast LPU (Requires Key / Free Tier Available)
  {
    id: 'groq-llama-3.3-70b',
    name: 'Llama 3.3 70B (Groq LPU)',
    displayName: 'Meta Llama 3.3 70B Versatile (450 t/s)',
    provider: 'Groq',
    providerModelId: 'llama-3.3-70b-versatile',
    tier: 'free',
    costPer1kTokens: '$0.00 (Groq Free Tier)',
    inputCost: '$0.00',
    outputCost: '$0.00',
    contextWindow: '128,000 tokens',
    status: 'untested',
    capabilities: ['coding', 'reasoning', 'fast'],
    codingScore: 90,
    online: true,
    isLocal: false,
    availability: 'requires_key'
  },

  // 5. Cloudflare Workers AI
  {
    id: 'cf-llama-3.1-8b',
    name: 'Llama 3.1 8B (Cloudflare)',
    displayName: 'Cloudflare Workers AI Llama 3.1',
    provider: 'Cloudflare',
    providerModelId: '@cf/meta/llama-3.1-8b-instruct',
    tier: 'free',
    costPer1kTokens: '$0.00 (Free Daily 10k Neurons)',
    inputCost: '$0.00',
    outputCost: '$0.00',
    contextWindow: '8,192 tokens',
    status: 'untested',
    capabilities: ['fast'],
    codingScore: 80,
    online: true,
    isLocal: false,
    availability: 'requires_key'
  },

  // 6. Paid Models (Safety Gate: Auto-Blocked, Requires Explicit Authorization)
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    displayName: 'Anthropic Claude 3.5 Sonnet (Paid)',
    provider: 'Anthropic',
    tier: 'paid_blocked',
    costPer1kTokens: '$0.003 in / $0.015 out',
    inputCost: '$3.00 / 1M',
    outputCost: '$15.00 / 1M',
    contextWindow: '200,000 tokens',
    status: 'untested',
    capabilities: ['coding', 'reasoning', 'vision', 'tool_use'],
    codingScore: 98,
    online: true,
    isLocal: false,
    availability: 'requires_auth'
  },
  {
    id: 'gpt-4o',
    name: 'OpenAI GPT-4o',
    displayName: 'OpenAI GPT-4o Omni (Paid)',
    provider: 'OpenAI',
    tier: 'paid_blocked',
    costPer1kTokens: '$0.0025 in / $0.010 out',
    inputCost: '$2.50 / 1M',
    outputCost: '$10.00 / 1M',
    contextWindow: '128,000 tokens',
    status: 'untested',
    capabilities: ['coding', 'reasoning', 'vision', 'tool_use'],
    codingScore: 94,
    online: true,
    isLocal: false,
    availability: 'requires_auth'
  },
  {
    id: 'o3-mini',
    name: 'OpenAI o3-mini',
    displayName: 'OpenAI o3-mini Reasoning (Paid)',
    provider: 'OpenAI',
    tier: 'paid_blocked',
    costPer1kTokens: '$0.0011 in / $0.0044 out',
    inputCost: '$1.10 / 1M',
    outputCost: '$4.40 / 1M',
    contextWindow: '200,000 tokens',
    status: 'untested',
    capabilities: ['reasoning', 'coding'],
    codingScore: 97,
    online: true,
    isLocal: false,
    availability: 'requires_auth'
  }
];
